### ISSUE TITLE
我是新手。请问一下send_email.jar在哪里？

### ISSUE THREAD

**Issue by Ryuukoushou** [nu0l/Send_Email#1]

**Comment by Ryuukoushou** [comment]
![image](https://github.com/user-attachments/assets/4a7780de-cb1c-4b71-80f4-0284b1ddc718)

**Comment by nu0l** [comment]
1. 下载界面在[releases界面](https://github.com/nu0l/Send_Email/releases)
![image](https://github.com/user-attachments/assets/353178c1-9362-4a45-a3c4-14426c76a873)

2. 下载jar文件后，使用jdk8环境运行`java -jar send_email.jar`命令，如果环境有问题，建议自行打包。
![image](https://github.com/user-attachments/assets/eb6e53cc-9199-4eba-9304-67fcaf594083)
