### ISSUE TITLE
web提供接口调用

### ISSUE THREAD

**Issue by Lsec-cyber** [nu0l/Send_Email#2]
web提供接口调用时会一直发送失败，而gui端却是可以

<img width="1086" alt="image" src="https://github.com/user-attachments/assets/ccce02a2-b967-47ac-ba98-db7ec8ae7944" />

**Comment by nu0l** [comment]
可以提供一下请求参数吗？

**Comment by Lsec-cyber** [comment]
POST /api/email/send HTTP/1.1
Host: 127.0.0.1:58090
Content-Length: 154
sec-ch-ua: "Not-A.Brand";v="99", "Chromium";v="124"
accept: */*
Content-Type: application/json
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.6367.118 Safari/537.36
sec-ch-ua-platform: "macOS"
Origin: http://127.0.0.1:58090
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://127.0.0.1:58090/1213300000/swagger-ui/index.html
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Cookie: JSESSIONID=5C090E255C2D2B512FF0A245BCA9AA61
Connection: keep-alive

{
  "to": [
    "1@qq.com"
  ],
  "subject": "",
  "content": "",
  "attachments": [
    {
      "fileName": "",
      "filePath": ""
    }
  ]
}
<img width="1163" alt="image" src="https://github.com/user-attachments/assets/9c6db702-6c9f-4757-b7af-3c2cdbe69cb7" />

我发现web端添加的配置，似乎无法改动gui读取的.config/sendEmail/config.properties 文件，是不是因为没有读到配置文件导致的

**Comment by Lsec-cyber** [comment]
图片复制错了
<img width="1213" alt="image" src="https://github.com/user-attachments/assets/17faaaed-f0ff-4ad7-bb63-9bcc86f1cabf" />

**Comment by nu0l** [comment]
大概知道什么问题了，web端的附件功能没有处理null的情况，晚点我更新下代码，修复此问题。🫡
```
"attachments": [
    {
      "fileName": "",
      "filePath": ""
    }
  ]
```

**Comment by Lsec-cyber** [comment]
好，辛苦师傅了，配置没啥问题，是我权限不对

**Comment by Lsec-cyber** [comment]
还有一个问题是指定附近文件名和路径后，会固定重命名为filename和filepath
<img width="692" alt="image" src="https://github.com/user-attachments/assets/054ac150-be29-4799-8b70-56b9e3a714be" />
<img width="628" alt="image" src="https://github.com/user-attachments/assets/59fc6fb1-0162-4a75-8f81-62ae476874b4" />

**Comment by nu0l** [comment]
已修复，师傅重新pull下试试。

**Comment by nu0l** [comment]
如果发送邮件不需要插入附件，则滞空为null
```
{
  "to": [
    "1xxx@qq.com"
  ],
  "subject": "邮件主题内容",
  "content": "邮件的正文内容",
  "attachments": [
    {
      "fileName": null,
      "filePath": null
    }
  ]
}
```
